# 文件路径: .github/workflows/publish.yaml
name: Deploy Website to GitHub Pages

on:
  # 在推送到 `main` 分支时运行
  push:
    branches: ["main"]
  # 允许你从 Actions 选项卡手动运行此工作流
  workflow_dispatch:

# 为部署到 GitHub Pages 设置权限
permissions:
  contents: read
  pages: write
  id-token: write

# 只允许一个并发部署，避免冲突
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # 构建任务
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 获取所有git历史记录，Hugo需要它来生成 .Lastmod 等信息

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.119.0' # 保持与你旧文件一致的版本
          extended: true

      - name: Setup Pages
        # 这是修复你构建命令中 baseURL 问题的关键步骤
        id: pages
        uses: actions/configure-pages@v5

      - name: Build with Hugo
        env:
          # HUGO_ENVIRONMENT is for Hugo's "production" mode
          HUGO_ENVIRONMENT: production
        run: |
          # 使用上一步 setup-pages 的输出来正确设置 baseURL
          hugo --minify --baseURL "${{ steps.pages.outputs.base_url }}/"

      - name: Upload artifact
        # 使用最新的 v3 版本，修复你的核心错误
        uses: actions/upload-pages-artifact@v3
        with:
          # Hugo 默认的输出路径
          path: ./public

  # 部署任务
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build # 依赖于 build 任务成功完成
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        # 使用最新的 v4 版本。
        uses: actions/deploy-pages@v4
